---
k3s_common_packages:
  - ca-certificates
  - curl
  - git
  - htop
  - mc
  - fish
  - openssh-server
  - sudo

k3s_common_public_key: ""
k3s_common_sshd_hardening_conf: /etc/ssh/sshd_config.d/00-homelab-hardening.conf
