---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hermes
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/ReveekJ/k8s_homelab.git
      targetRevision: main
      path: gitops/apps/hermes/chart
      helm:
        valueFiles:
          - $values/gitops/values-common.yaml
          - values.yaml
    - repoURL: https://github.com/ReveekJ/k8s_homelab.git
      targetRevision: main
      path: gitops/apps/hermes
      kustomize: {}
    - repoURL: https://github.com/ReveekJ/k8s_homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: hermes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
