---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hermes
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:example/k8s_homelab.git
    targetRevision: main
    path: gitops/apps/hermes/chart
    helm:
      valueFiles:
        - $ARGOCD_APP_PROJECT/../values-common.yaml
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: hermes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
