apiVersion: ENC[AES256_GCM,data:EsM=,iv:THy+YjUgPQX8Nm9UYmnfg9mAYTaU5YzQ/Yg8iu3QNNw=,tag:sUjryv9NuaWyQ9YMt/DZOw==,type:str]
kind: ENC[AES256_GCM,data:S1Vk+jvk,iv:8oXCx2+DY2Ua6Q/WONDFgmwwrGK7ewGhVP4ALJVe368=,tag:8Eagrby5DDmBy1BVGrW6pw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HrGFe1OM2WgtVc3gmUI=,iv:yFERoJFTB25S2UB1fRSw7RoBmvQUPGiB4hvZns9nGN4=,tag:QZx12lK44nRn1nnJ30myNQ==,type:str]
    namespace: ENC[AES256_GCM,data:L6zAw+k7,iv:ZdHGmtwDvBU+WerwsQvlcSmMzaeO572yxTVPps6dyS4=,tag:ly/Xhuu304C2khIfYR/x9w==,type:str]
type: ENC[AES256_GCM,data:sF6vnStE,iv:cbLqdqnKLGw+W0YH2y67dAgVQzyvD9KPtFjMNaJHqfo=,tag:p8J3pB1e8JCS3n/70gzWVg==,type:str]
stringData:
    HERMES_CUSTOM_DDTNEW_COM_API_KEY: ENC[AES256_GCM,data:BAHWvgpE7IX+5VlmLYpxs2y4r7/Rx2gfJPMxBJCE6ls=,iv:PySzGXl7I4YsQDbOqESPJT6j5rHHAbNOX6CZe0fMYnI=,tag:5/cl0Cd3anQddXh2p6O3bg==,type:str]
    HERMES_API_SERVER_KEY: ENC[AES256_GCM,data:AuODf4e+NZYtI31QbjkOpVY734/4ltF8fGnPDp11CKBL,iv:QifkdKkXMCXVQBqnlLiDfqkVvz62T/dmxlbCmZsFv98=,tag:Q9PYzEVM45U0iDTRRNZSsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdnF6TUplSjZWUVJUcDF5
            aVRQcWhOVHVqRkJPMG1WVWg2ekdPVGlwTG1vCkRyeTl2MUZ3dUtRd1BXWTZNKzBP
            czNCTnkvamRpM2JiS1AwVkZBT1VtQTAKLS0tIGdZUU10T295MzJqeGcrSmJjeURY
            YW1SS1NINXNIeHJwVkpETHV5djg2RzAKYdZInJYeb0NA8oUiOvWPSvrPadeVMrK3
            G34ndkrJ68r+wry382wqsK9MLHfoU1UfzHgHdvOU7uSdiLkDVcP+8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19fuquw740yzaljg4mzph5ejxkgwvnhp4xu9hu53s27s2g7w60uqqcg76qz
    lastmodified: "2026-09-13T14:41:57Z"
    mac: ENC[AES256_GCM,data:mT274Bjc0kmF7BSJeq8nsb5KPL74vPSHXCCvp0wfaUrMqrVQ7zoCFPsMeoyxejPQGpt0lkm1FRs3xrjeZjMD7rXKYsL5ndsZQ7Q6Vb8o5q2zN5FmjdCNIznnxbSteQyOaSFbfDg1+jabYZcgbfV+n3U918ZhPbtXIIgdlOKtUwo=,iv:ndF1hQusrvyenqkVMJ3Tj2tdWNq633nOIPUxiQwG6Pc=,tag:X+bbsbL+pzmjBg+Gt5/Xog==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
