apiVersion: ENC[AES256_GCM,data:qBM=,iv:3YEtGFHSHsnViV1MrkkUmnKC1DJlUbvXJFYdZnLyljg=,tag:5agmYlzfDdqitqfoBmEQog==,type:str]
kind: ENC[AES256_GCM,data:WQNaTpAT,iv:syMVcn2UHwJ+Tb20wH2uoQHJxKHiX1YNBwg3tW09RS8=,tag:dFx5fKtEgvkOKe7mEfud7A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PDkZDPPkt1BTi9wW,iv:/BVXypzeSyyWgcsF0l64ynkKLWUPjKkwbLhgdKS9CYw=,tag:l3z1K+d+kiuGMrX1o8r+mA==,type:str]
    namespace: ENC[AES256_GCM,data:zUaaCgfx,iv:tBfRFA65kreTF90QE7L4N9q3h1Zt5VzowNRUZ2pwfyQ=,tag:2VZ5N4HZ3bCig22gGW4zyQ==,type:str]
type: ENC[AES256_GCM,data:g1cSswv6,iv:yDSU8WyJI5H4qzBcRI8I8V+yqZViUceINPZdgjKpKzc=,tag:HoPNvR7UQzOGOb66GEjPUA==,type:str]
stringData:
    key.txt: ENC[AES256_GCM,data:ooIgzrUiFu84NfTZ9w5Ol13gDw==,iv:mYhi38GchW7v85HEqcZ7BEar/HXSi2kXx8tZMOxMZ/E=,tag:WtqZRxiscfCoq7n3WosGiw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvL1RVM1FFLzFtNGRTSlhz
            Ri9BZjBuaERvQmsyM2hQOFI1NHUySkhQYldnClJSRE43d2VFUk5lbHhBZTRmM3pk
            dDU1K0ZCcGk4V0tMVTQwaHJMNFJybHMKLS0tIE1rcXpmeFV1ZU4xQTVidHJuMzZ0
            SGJZeFcvRUgydmlqVktyUS9BTEM0T1EKsskNT91syYG7irBWKxf3sEmW1cm/JrKE
            1g4KaWVMCJrS6hVgJtLDX8hBW6vtd6FiKMO2mYGZd/ZxLW54j2UQaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19fuquw740yzaljg4mzph5ejxkgwvnhp4xu9hu53s27s2g7w60uqqcg76qz
    lastmodified: "2026-09-13T14:45:13Z"
    mac: ENC[AES256_GCM,data:oUfi7hPdDgcuhj1cinonHJYDINknnPKrue/0o72Htx5BAnAJj3b79A9JDynbdBF8mK8f1hDSG34QSRDQzccyktJd8M27wbIzZsDq87k6s87xGNDKVRZUmjfr6MF78h6t9U98NzO/2bxe8NRYnEGsCuhy7bz97BsqNAZGm6d2wh8=,iv:KsCClvBfV50vQSDA+qUHFMY8+03yH1e1Kmy2ll4Nyrw=,tag:FYap4X5is+TvLG+pfBjJjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
