apiVersion: ENC[AES256_GCM,data:PHQ=,iv:IvcRGxOCoYu757pqhKMfhi5TF52iewgv7bxXWY+hSqU=,tag:ewkU49ixr/Crlx91GCYfkA==,type:str]
kind: ENC[AES256_GCM,data:hm9wNAfN,iv:feytcZKKVd0ZU8vNcqfGyOHk+/u2w2OID3yvbmqWO8g=,tag:7L6jtVho4S0vTCXJempA+Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DjtiJwrZs21RzdF3hw==,iv:HoCvG7CEPRv0dnEwm6W6iK/X64xe/3STFDAtrZ9fsu0=,tag:yU73K2otA8TQNI2MGgrSXA==,type:str]
    namespace: ENC[AES256_GCM,data:ulXnnc7vMB4=,iv:uqVFxWt9c8n/TgZ0SRkYmelKFy5qBi8i3leaHxPJcmU=,tag:h9/3Df8fDvs0z6oAl7nUbQ==,type:str]
type: ENC[AES256_GCM,data:YycgASLA,iv:06bqtawkTOIKnbne3555pmz7axi6VIqknNnYSQJ2j1I=,tag:YtM6GKPPTCVJhuLjcXzIlQ==,type:str]
stringData:
    htpasswd: ENC[AES256_GCM,data:gB0KQql3kSRU5/fWC+MuOaiwc3zJyKXceXMhv0Y=,iv:sovahlK/EzCFqq/eJJY5OOwrBGNrEnon/m8tzMZqMC4=,tag:DnmRdHE9FZkv+khL6OiHnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdmV2N1JpaGNaRkVreS9s
            eVFYdkRlYThDQzhjSDJkUDJJdWc5d2dvOFdnClpwREpsSUhXc0ZNNlhxZDYxQW1K
            WjRJMXVLWEhFTm1tZklkcnFEeFNMY0EKLS0tIHN4RFkzM0ZOZ1pwQ3dhYXJBNnJ0
            ams0NXBwYWhuaU5oSjVsazlYejg3Q0UK1jbmgql1/ON7hBiy52ey6p0FcRvoMeI4
            8RVZCzsWuG2svKne3rGaRE6d9URKnM394HqJ6vC7OR2ZyipnLjqTDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19fuquw740yzaljg4mzph5ejxkgwvnhp4xu9hu53s27s2g7w60uqqcg76qz
    lastmodified: "2026-09-13T14:41:57Z"
    mac: ENC[AES256_GCM,data:8kqTIAD8HuLEt+nL6PRopMKfEptiA4r62K8sPwF1ZXoO36VJ/gOlW6KRgVuFC5TBoihT6k7d832FsfXqh7sIE/knFXZKxzcwaU0LxVP6Uv/tsknsIjp6Sfh4jMtq1lPPb5j1vDGSFGjmIA4X25JqoP2TX8tsOANGLu9kd4xLumk=,iv:k5NQwVXcyf4i5vw2fo8WOV2UgL5MyByuX1FuG40qNAk=,tag:i6K4NVX0UtKWoZ6VwX1xqg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
