apiVersion: ENC[AES256_GCM,data:Rqw=,iv:K1LVCOyHiYBrXbIL/Cj85ipDJtu/RzC3WFgqFxE9wTo=,tag:aWP9yeEDt1vIKyRPUxF0tA==,type:str]
kind: ENC[AES256_GCM,data:4yYbXr6L,iv:F0DNl8R1m4715uZ7kEJUYCbtJofgj4mOoFquExfh8y4=,tag:vq71ARe1O78XDr7IbvTwQQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sBVeCqeQUf09Uc51cw==,iv:ErGu5w9bzgMOvg6Bx07zqWWxtxC2KL+TcjZxbNYNsKM=,tag:5LQNsuIfUHjYNiX3opv3Fg==,type:str]
    namespace: ENC[AES256_GCM,data:StyzXZpRttq7,iv:vBiHlcwNmQMmiybWHkhjvxSZzSSoZI9KLOGW6xVvogM=,tag:3oJBGO3WU9fol8GCw+tfag==,type:str]
type: ENC[AES256_GCM,data:Nc2eCz5e,iv:S0e0npo788O0R+jynjDhOKLS2WGVsXQDHiTR0NU67dA=,tag:8am5X+OpVBW4kTO9AN3/Ng==,type:str]
stringData:
    htpasswd: ENC[AES256_GCM,data:Hg9NFVOs9T15k7U6Mf2SWSyvIYy48LhuC7mXUYY=,iv:sOs1SX/56FnPvojMD+3AxdzLGOre2VGyYTzXxBf7mm0=,tag:HF3jIWBtM2wA4o4kMt4/7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVEhLaXhxcDgwMkRNZWE2
            ZnhtOUtMVlUrNFg2M2lqOTFmZk1wdHZxc1JjClgxbXVuOVI5MXR2QS9oRlVBZVA5
            Qk9zcGZmY1ROSVFXajk0Q1lIWC9RdmMKLS0tIHQrb0I5blJEcmF4cDh0WkQvYUJw
            ODFxRUl4cHl1LzA1VmRqNGFvbzFRNm8KAm12MQ6imDMxmcVgWAr3YAogooVMZiud
            jL9IyFSZo4ilUmdyf5jOn8oK6RMC0xBBEh7eGxYC/2FZijgfJ2qnOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19fuquw740yzaljg4mzph5ejxkgwvnhp4xu9hu53s27s2g7w60uqqcg76qz
    lastmodified: "2026-09-14T02:45:28Z"
    mac: ENC[AES256_GCM,data:wahL9089toF1ZlDqgYdalVUlSJUWSYkLAeuLAAlcx73h9UAjxvIlkJF0wgxhfBJN6QAn06tJImN1HVOO1hJyJw4FepBJmtB8BfLbpCuJxGiE9stp8reBHLyZbcSZii1vRsxBqvGjD+JEMCq+CLJLD5l4hvNN+LJoIsbrG4IfMJQ=,iv:05koALMDP0SYkwdGv5ur4R/yp6Rh/KBOgwDdOcTsECE=,tag:ezIk3TFyPrn/WSrVqxcPdw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
